# Generated by Django 3.1.1 on 2020-12-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bTitle', models.CharField(max_length=200)),
                ('bImage', models.ImageField(upload_to='')),
                ('book', models.FileField(upload_to='books')),
                ('bPriority', models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], default='1', max_length=20)),
            ],
        ),
    ]
