# Generated by Django 3.1.1 on 2020-12-24 07:39

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20201222_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vName', models.CharField(max_length=200)),
                ('vUrl', embed_video.fields.EmbedVideoField(blank=True)),
                ('vPriority', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
            ],
        ),
    ]
