# Generated by Django 3.1.1 on 2021-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
