# Generated by Django 3.1.1 on 2021-01-22 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='bPriority',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='vPriority',
        ),
        migrations.AddField(
            model_name='books',
            name='bDescip',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='vCreator',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='vDescip',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
